import { Item, CharacterClass } from '../types/game';

export type ShopId = 'blacksmith' | 'potions' | 'equipment' | 'general' | 'mystic';

export interface ShopItem {
  item: Item;
  price: number;
  stock?: number;
  forClass?: CharacterClass | 'all';
  requiredLevel?: number;
  tag?: string;
}

export interface ShopConfig {
  id: ShopId;
  title: string;
  subtitle: string;
  npcName: string;
  npcRole: string;
  avatarIcon: string;
  greeting: string;
  location: string;
  canEnhance?: boolean;
  items: ShopItem[];
}

export const SHOPS: Record<ShopId, ShopConfig> = {
  blacksmith: {
    id: 'blacksmith',
    title: 'Bengkel Tempa & Senjata Master Torvald',
    subtitle: 'Senjata Baja Ditempa Kuno & Peningkatan Perlengkapan',
    npcName: 'Master Torvald',
    npcRole: 'Pandai Besi Legendaris Eldoria',
    avatarIcon: '🔨',
    greeting: 'Dentang! Selamat datang di api tempaku! Butuh pedang baja tajam, tongkat sihir berenergi, busur akurat, atau ingin menaikkan tingkat senjatamu?',
    location: 'Sisi Barat Alun-Alun Desa Eldoria',
    canEnhance: true,
    items: [
      // Warrior Weapons
      {
        item: {
          id: 'sword_knight_iron',
          name: 'Knight Broadsword',
          nameId: 'Pedang Baja Ksatria',
          type: 'weapon',
          rarity: 'common',
          description: 'A heavy forged broadsword with razor-sharp balance.',
          descriptionId: 'Pedang lebar baja tempa berat dengan keseimbangan tebasan luar biasa.',
          icon: '🗡️',
          value: 70,
          stats: { attack: 16, defense: 4 },
        },
        price: 70,
        forClass: 'warrior',
        tag: 'Ksatria',
      },
      {
        item: {
          id: 'sword_flame_crystal',
          name: 'Blazing Claymore',
          nameId: 'Pedang Kristal Bara Api',
          type: 'weapon',
          rarity: 'rare',
          description: 'Imbued with molten magma cores, scorching enemies with each strike.',
          descriptionId: 'Ditempa dengan inti magma cair, membakar musuh pada setiap tebasan.',
          icon: '🔥',
          value: 190,
          stats: { attack: 30, hp: 35 },
        },
        price: 190,
        forClass: 'warrior',
        requiredLevel: 2,
        tag: 'Ksatria',
      },
      {
        item: {
          id: 'axe_berserker',
          name: 'Berserker Cleaver',
          nameId: 'Kapak Perang Berantai',
          type: 'weapon',
          rarity: 'epic',
          description: 'Colossal battleaxe that cleaves through stone and armor alike.',
          descriptionId: 'Kapak perang raksasa pemecah zirah baja dan batu dengan kekuatan dahsyat.',
          icon: '🪓',
          value: 360,
          stats: { attack: 44, defense: 8 },
        },
        price: 360,
        forClass: 'warrior',
        requiredLevel: 3,
        tag: 'Ksatria',
      },

      // Mage Weapons
      {
        item: {
          id: 'staff_apprentice_wood',
          name: 'Runed Oak Staff',
          nameId: 'Tongkat Kayu Ek Bertuliskan Rune',
          type: 'weapon',
          rarity: 'common',
          description: 'Channeled wooden staff conducting arcane lightning pulses.',
          descriptionId: 'Tongkat kayu ek kuno bertatahkan rune pemusat aliran sihir.',
          icon: '🪄',
          value: 65,
          stats: { attack: 14, mp: 30 },
        },
        price: 65,
        forClass: 'mage',
        tag: 'Penyihir',
      },
      {
        item: {
          id: 'staff_azure_starlight',
          name: 'Starlight Scepter',
          nameId: 'Tongkat Bintang Azure',
          type: 'weapon',
          rarity: 'rare',
          description: 'Focuses radiant cosmic energy for blinding arcane barrages.',
          descriptionId: 'Memusatkan energi kosmik bercahaya untuk semburan sihir dahsyat.',
          icon: '✨',
          value: 180,
          stats: { attack: 28, mp: 65 },
        },
        price: 180,
        forClass: 'mage',
        requiredLevel: 2,
        tag: 'Penyihir',
      },
      {
        item: {
          id: 'staff_tempest_archmage',
          name: 'Tempest Archon Rod',
          nameId: 'Tongkat Badai Petir Mistik',
          type: 'weapon',
          rarity: 'epic',
          description: 'Crackles with raw lightning and destructive void vortexes.',
          descriptionId: 'Mengeluarkan kilatan petir murni dan pusaran sihir kehancuran.',
          icon: '⚡',
          value: 380,
          stats: { attack: 42, mp: 95 },
        },
        price: 380,
        forClass: 'mage',
        requiredLevel: 3,
        tag: 'Penyihir',
      },

      // Rogue Weapons (Daggers & Bows)
      {
        item: {
          id: 'daggers_shadow_twin',
          name: 'Twin Shadow Daggers',
          nameId: 'Belati Bayangan Kembar',
          type: 'weapon',
          rarity: 'common',
          description: 'Pair of balanced steel daggers with serrated quick-strike edges.',
          descriptionId: 'Sepasang belati baja seimbang dengan gerigi tajam untuk serangan kilat.',
          icon: '🗡️',
          value: 65,
          stats: { attack: 15, speed: 4 },
        },
        price: 65,
        forClass: 'rogue',
        tag: 'Pemburu',
      },
      {
        item: {
          id: 'bow_elven_composite',
          name: 'Elven Composite Bow',
          nameId: 'Busur Pemburu Hutan Elven',
          type: 'weapon',
          rarity: 'rare',
          description: 'Supple recurve bow launching arrows with piercing accuracy.',
          descriptionId: 'Busur panah melengkung lentur dengan akurasi tembakan tembus zirah.',
          icon: '🏹',
          value: 175,
          stats: { attack: 27, speed: 6 },
        },
        price: 175,
        forClass: 'rogue',
        requiredLevel: 2,
        tag: 'Pemburu',
      },
      {
        item: {
          id: 'daggers_viper_fang',
          name: 'Viper Fang Daggers',
          nameId: 'Taring Belati Beracun Viper',
          type: 'weapon',
          rarity: 'rare',
          description: 'Coated with deadly forest venom that seeps through enemy defenses.',
          descriptionId: 'Dilumuri bisa racun mematikan hutan yang meremukkan pertahanan musuh.',
          icon: '🐍',
          value: 240,
          stats: { attack: 35, speed: 8 },
        },
        price: 240,
        forClass: 'rogue',
        requiredLevel: 3,
        tag: 'Pemburu',
      },
      {
        item: {
          id: 'bow_windrunner_legend',
          name: 'Windrunner Storm Bow',
          nameId: 'Busur Badai Bayangan',
          type: 'weapon',
          rarity: 'epic',
          description: 'A masterpiece bow singing with gales of razor wind arrows.',
          descriptionId: 'Busur mahakarya yang bersiul bersama desingan anak panah badai.',
          icon: '🌪️',
          value: 390,
          stats: { attack: 43, speed: 9 },
        },
        price: 390,
        forClass: 'rogue',
        requiredLevel: 3,
        tag: 'Pemburu',
      },
    ],
  },

  potions: {
    id: 'potions',
    title: 'Apotik & Toko Ramuan Alkemis Anya',
    subtitle: 'Ramuan Penyembuh Alami, Eliksir Mana, & Tonik Stamina',
    npcName: 'Anya the Herbalist',
    npcRole: 'Alkemis & Herbalis Eldoria',
    avatarIcon: '🌿',
    greeting: 'Salam, pengelana! Ramuan herbal segar baru saja saya saring dari akar hutan mistis. Selalu siapkan ramuan pemulih sebelum bertualang ke sarang monster!',
    location: 'Sisi Timur Alun-Alun Desa Eldoria',
    canEnhance: false,
    items: [
      {
        item: {
          id: 'potion_hp_small',
          name: 'Minor Health Potion',
          nameId: 'Ramuan Darah Kecil',
          type: 'consumable',
          rarity: 'common',
          description: 'Restores 45 HP instantly.',
          descriptionId: 'Memulihkan 45 HP seketika.',
          icon: '🧪',
          value: 15,
          consumableEffect: { hpRestore: 45 },
        },
        price: 15,
        tag: 'HP',
      },
      {
        item: {
          id: 'potion_hp_medium',
          name: 'Vitality Draught',
          nameId: 'Ramuan Darah Sedang',
          type: 'consumable',
          rarity: 'common',
          description: 'Restores 90 HP instantly.',
          descriptionId: 'Memulihkan 90 HP seketika.',
          icon: '🧪',
          value: 35,
          consumableEffect: { hpRestore: 90 },
        },
        price: 35,
        tag: 'HP',
      },
      {
        item: {
          id: 'potion_hp_large',
          name: 'Greater Elixir of Life',
          nameId: 'Eliksir Kehidupan Murni',
          type: 'consumable',
          rarity: 'rare',
          description: 'Restores 160 HP completely.',
          descriptionId: 'Memulihkan 160 HP secara penuh.',
          icon: '💖',
          value: 65,
          consumableEffect: { hpRestore: 160 },
        },
        price: 65,
        tag: 'HP Super',
      },
      {
        item: {
          id: 'potion_mp_small',
          name: 'Minor Mana Potion',
          nameId: 'Ramuan Mana Kecil',
          type: 'consumable',
          rarity: 'common',
          description: 'Restores 40 MP instantly.',
          descriptionId: 'Memulihkan 40 MP seketika.',
          icon: '💧',
          value: 15,
          consumableEffect: { mpRestore: 40 },
        },
        price: 15,
        tag: 'MP',
      },
      {
        item: {
          id: 'potion_mp_medium',
          name: 'Arcane Draught',
          nameId: 'Ramuan Mana Murni',
          type: 'consumable',
          rarity: 'common',
          description: 'Restores 85 MP instantly.',
          descriptionId: 'Memulihkan 85 MP seketika.',
          icon: '💧',
          value: 35,
          consumableEffect: { mpRestore: 85 },
        },
        price: 35,
        tag: 'MP',
      },
      {
        item: {
          id: 'potion_mp_large',
          name: 'Celestial Mana Elixir',
          nameId: 'Eliksir Bintang Arcanist',
          type: 'consumable',
          rarity: 'rare',
          description: 'Restores 150 MP completely.',
          descriptionId: 'Memulihkan 150 MP secara penuh.',
          icon: '✨',
          value: 65,
          consumableEffect: { mpRestore: 150 },
        },
        price: 65,
        tag: 'MP Super',
      },
      {
        item: {
          id: 'potion_rejuvenation_grand',
          name: 'Grand Rejuvenation Draught',
          nameId: 'Eliksir Rejuvenasi Agung',
          type: 'consumable',
          rarity: 'epic',
          description: 'Restores 140 HP and 120 MP simultaneously.',
          descriptionId: 'Memulihkan 140 HP dan 120 MP sekaligus secara instan!',
          icon: '🌟',
          value: 110,
          consumableEffect: { hpRestore: 140, mpRestore: 120 },
        },
        price: 110,
        tag: 'HP + MP',
      },
      {
        item: {
          id: 'potion_antidote_forest',
          name: 'Purifying Herb Tonic',
          nameId: 'Tonik Pembersih Racun Herbal',
          type: 'consumable',
          rarity: 'common',
          description: 'Neutralizes toxic venom and restores 50 HP.',
          descriptionId: 'Menetralisir racun laba-laba dan memulihkan 50 HP.',
          icon: '🍃',
          value: 25,
          consumableEffect: { hpRestore: 50 },
        },
        price: 25,
        tag: 'Herbal',
      },
    ],
  },

  equipment: {
    id: 'equipment',
    title: 'Toko Perlengkapan & Zirah Maya',
    subtitle: 'Pelindung Tubuh, Zirah Ksatria, Jubah Mistik, & Cincin Berdaya',
    npcName: 'Maya the Outfitter',
    npcRole: 'Pedagang Zirah & Perlengkapan Tempur',
    avatarIcon: '🛡️',
    greeting: 'Selamat datang di Toko Zirah! Zirah yang kokoh dan cincin berdaya magis adalah pembeda antara hidup dan mati saat menghadapi musuh!',
    location: 'Sisi Selatan Alun-Alun Desa Eldoria',
    canEnhance: false,
    items: [
      {
        item: {
          id: 'armor_steel_plate',
          name: 'Tempered Iron Breastplate',
          nameId: 'Zirah Pelat Baja Tempa',
          type: 'armor',
          rarity: 'common',
          description: 'Heavy solid steel chest armor providing reliable protection.',
          descriptionId: 'Zirah dada baja tempa pejal pemberi pertahanan fisik yang tangguh.',
          icon: '🛡️',
          value: 90,
          stats: { defense: 12, hp: 40 },
        },
        price: 90,
        tag: 'Zirah',
      },
      {
        item: {
          id: 'armor_dragon_scale',
          name: 'Bronze Dragon Scale Armor',
          nameId: 'Zirah Tempur Sisik Naga',
          type: 'armor',
          rarity: 'rare',
          description: 'Interlocking bronze scales deflecting heavy claws and blows.',
          descriptionId: 'Sisik naga perunggu berkait yang menangkis cakar tajam dan hantaman keras.',
          icon: '🐉',
          value: 210,
          stats: { defense: 22, hp: 85 },
        },
        price: 210,
        requiredLevel: 2,
        tag: 'Zirah',
      },
      {
        item: {
          id: 'armor_paladin_aegis',
          name: 'Holy Aegis Plate',
          nameId: 'Zirah Ksatria Suci Paladin',
          type: 'armor',
          rarity: 'epic',
          description: 'Consecrated armor radiating a blessed golden aura.',
          descriptionId: 'Zirah suci berkilau emas dengan daya tahan luar biasa terhadap segala serangan.',
          icon: '⚜️',
          value: 390,
          stats: { defense: 32, hp: 140 },
        },
        price: 390,
        requiredLevel: 3,
        tag: 'Zirah Legendaris',
      },
      {
        item: {
          id: 'armor_mystic_robe',
          name: 'Enchanted Arcane Robe',
          nameId: 'Jubah Sutra Mistik Bintang',
          type: 'armor',
          rarity: 'common',
          description: 'Woven with star-threads, boosting mana reservoirs.',
          descriptionId: 'Ditenun dari benang bintang, memperbesar kapasitas cadangan mana.',
          icon: '👘',
          value: 85,
          stats: { defense: 8, mp: 60 },
        },
        price: 85,
        tag: 'Jubah',
      },
      {
        item: {
          id: 'armor_shadow_vest',
          name: 'Stalker Leather Jerkin',
          nameId: 'Rompi Pengintai Kulit Halus',
          type: 'armor',
          rarity: 'common',
          description: 'Supple beast leather allowing lightning agility and quiet steps.',
          descriptionId: 'Rompi kulit binatang lentur untuk pergerakan gesit dan senyap.',
          icon: '🦺',
          value: 85,
          stats: { defense: 9, speed: 4, hp: 35 },
        },
        price: 85,
        tag: 'Rompi',
      },
      {
        item: {
          id: 'ring_ruby_vitality',
          name: 'Ruby Ring of Vitality',
          nameId: 'Cincin Delima Darah',
          type: 'accessory',
          rarity: 'rare',
          description: 'A crimson gemstone constantly infusing vital blood warmth.',
          descriptionId: 'Batu delima merah membara yang memperkuat daya tahan hidup pemakainya.',
          icon: '💍',
          value: 125,
          stats: { hp: 70, defense: 6 },
        },
        price: 125,
        tag: 'Aksesori',
      },
      {
        item: {
          id: 'ring_sapphire_wisdom',
          name: 'Sapphire Ring of Wisdom',
          nameId: 'Cincin Safir Kebijaksanaan',
          type: 'accessory',
          rarity: 'rare',
          description: 'Deep ocean sapphire resonating with vast mana tides.',
          descriptionId: 'Batu safir biru laut dalam yang mengalirkan energi mana tak terbatas.',
          icon: '💎',
          value: 130,
          stats: { mp: 80, attack: 8 },
        },
        price: 130,
        tag: 'Aksesori',
      },
      {
        item: {
          id: 'helm_iron_sentinel',
          name: 'Sentinel Steel Visor',
          nameId: 'Helm Tempur Pelindung Baja',
          type: 'accessory',
          rarity: 'common',
          description: 'Sturdy steel helm protecting head and neck in violent skirmishes.',
          descriptionId: 'Helm baja tempa kokoh pelindung kepala dari serangan mendadak.',
          icon: '🪖',
          value: 95,
          stats: { defense: 10, hp: 45 },
        },
        price: 95,
        tag: 'Helm',
      },
    ],
  },

  general: {
    id: 'general',
    title: 'Kios Pesisir & Hasil Laut Pak Joko',
    subtitle: 'Makanan Laut Bernutrisi, Perbekalan Petualang, & Harta Karun Pantai',
    npcName: 'Pak Joko Nelayan',
    npcRole: 'Nelayan Pesisir Pantai Selatan',
    avatarIcon: '🎣',
    greeting: 'Halo kawan muda! Angin laut selatan segar sekali hari ini! Mau perbekalan ikan bakar rempah segar penambah tenaga, atau mutiara laut berkilau?',
    location: 'Dermaga Kayu Pantai Azure (Selatan)',
    canEnhance: false,
    items: [
      {
        item: {
          id: 'food_grilled_fish',
          name: 'Spiced Grilled Snapper',
          nameId: 'Ikan Bakar Rempah Pesisir',
          type: 'consumable',
          rarity: 'common',
          description: 'Delicious fresh fish grilled over coconut coals. Restores 60 HP and 35 MP.',
          descriptionId: 'Ikan bakar segar lezat dengan bumbu rempah kelapa. Memulihkan 60 HP dan 35 MP.',
          icon: '🐟',
          value: 25,
          consumableEffect: { hpRestore: 60, mpRestore: 35 },
        },
        price: 25,
        tag: 'Makanan',
      },
      {
        item: {
          id: 'food_ocean_stew',
          name: 'Fisherman Seafood Broth',
          nameId: 'Sup Gurih Laut Selatan',
          type: 'consumable',
          rarity: 'rare',
          description: 'Rich seafood broth packed with stamina and health revitalizers. Restores 100 HP and 60 MP.',
          descriptionId: 'Sup sari laut kaya nutrisi pemulih stamina. Memulihkan 100 HP dan 60 MP.',
          icon: '🍲',
          value: 50,
          consumableEffect: { hpRestore: 100, mpRestore: 60 },
        },
        price: 50,
        tag: 'Makanan',
      },
      {
        item: {
          id: 'pearl_ocean_blessing',
          name: 'Luminescent Deep Pearl',
          nameId: 'Mutiara Laut Berkilau',
          type: 'accessory',
          rarity: 'rare',
          description: 'Harvested from abyssal clams, granting the blessing of the tides.',
          descriptionId: 'Dipanen dari kerang laut dalam, memberikan berkat perlindungan pasang laut.',
          icon: '🔮',
          value: 140,
          stats: { defense: 10, mp: 50, speed: 3 },
        },
        price: 140,
        tag: 'Pesisir',
      },
      {
        item: {
          id: 'compass_mariner',
          name: 'Mariner Ancient Compass',
          nameId: 'Teropong Navigasi Pelaut',
          type: 'accessory',
          rarity: 'common',
          description: 'Gilded brass compass pointing steadfastly toward safety and treasure.',
          descriptionId: 'Kompas kuningan berlapis emas yang menuntun arah petualangan.',
          icon: '🧭',
          value: 80,
          stats: { attack: 6, speed: 4 },
        },
        price: 80,
        tag: 'Navigasi',
      },
    ],
  },

  mystic: {
    id: 'mystic',
    title: 'Pasar Gelap & Artefak Kuno Kael',
    subtitle: 'Barang Antik Misterius, Rune Gelap, & Pusaka Langka',
    npcName: 'Kael the Scout',
    npcRole: 'Pedagang Pasar Gelap & Penjelajah Reruntuhan',
    avatarIcon: '🧑',
    greeting: 'Ssst... mendekatlah kawan. Aku menemukan beberapa artefak kuno di kedalaman reruntuhan barat. Harganya tidak murah, tapi kekuatannya tak tertandingi!',
    location: 'Sudut Tersembunyi Desa Eldoria',
    canEnhance: false,
    items: [
      {
        item: {
          id: 'rune_obsidian_core',
          name: 'Obsidian Titan Fragment',
          nameId: 'Pecahan Inti Titan Obsidian',
          type: 'accessory',
          rarity: 'epic',
          description: 'Pulsing fragment of ancient volcanic basalt. Radiates crushing attack power.',
          descriptionId: 'Pecahan inti basalt gunung api kuno yang berdenyut kekuatan serang destruktif.',
          icon: '🖤',
          value: 320,
          stats: { attack: 22, defense: 10, hp: 50 },
        },
        price: 320,
        requiredLevel: 2,
        tag: 'Artefak Kuno',
      },
      {
        item: {
          id: 'amulet_void_stalker',
          name: 'Amulet of the Abyssal Void',
          nameId: 'Jimat Bayangan Abadi',
          type: 'accessory',
          rarity: 'legendary',
          description: 'Forged in shadowy depths, gifting extreme speed and deadly strikes.',
          descriptionId: 'Ditempa di kedalaman bayangan, memberikan kecepatan kilat dan tebasan mematikan.',
          icon: '🧿',
          value: 460,
          stats: { attack: 30, speed: 8, mp: 60 },
        },
        price: 460,
        requiredLevel: 3,
        tag: 'Legendaris',
      },
      {
        item: {
          id: 'elixir_dragon_essence',
          name: 'Ancient Dragon Blood Elixir',
          nameId: 'Eliksir Darah Naga Kuno',
          type: 'consumable',
          rarity: 'epic',
          description: 'Forbidden draught instantly restoring 260 HP and 180 MP.',
          descriptionId: 'Ramuan terlarang yang seketika memulihkan 260 HP dan 180 MP seutuhnya!',
          icon: '🩸',
          value: 150,
          consumableEffect: { hpRestore: 260, mpRestore: 180 },
        },
        price: 150,
        tag: 'Ramuan Rahasia',
      },
      {
        item: {
          id: 'dagger_nether_crystal',
          name: 'Nether Crystal Blade',
          nameId: 'Belati Kristal Neraka Hitam',
          type: 'weapon',
          rarity: 'epic',
          description: 'Blade fashioned from hardened volcanic obsidian crystals.',
          descriptionId: 'Belati mematikan yang diasah dari kristal obsidian hitam gunung berapi.',
          icon: '🗡️',
          value: 380,
          stats: { attack: 44, speed: 8 },
        },
        price: 380,
        requiredLevel: 3,
        tag: 'Senjata Rahasia',
      },
    ],
  },
};
