import { Item, Quest, DialogueNode } from '../types/game';

export const INITIAL_ITEMS: Item[] = [
  {
    id: 'potion_hp_small',
    name: 'Minor Health Potion',
    nameId: 'Ramuan Darah Kecil',
    type: 'consumable',
    rarity: 'common',
    description: 'Restores 40 HP instantly.',
    descriptionId: 'Memulihkan 40 HP seketika.',
    icon: '🧪',
    value: 15,
    consumableEffect: { hpRestore: 40 },
  },
  {
    id: 'potion_hp_small_2',
    name: 'Minor Health Potion',
    nameId: 'Ramuan Darah Kecil',
    type: 'consumable',
    rarity: 'common',
    description: 'Restores 40 HP instantly.',
    descriptionId: 'Memulihkan 40 HP seketika.',
    icon: '🧪',
    value: 15,
    consumableEffect: { hpRestore: 40 },
  },
  {
    id: 'potion_mp_small',
    name: 'Minor Mana Potion',
    nameId: 'Ramuan Mana Kecil',
    type: 'consumable',
    rarity: 'common',
    description: 'Restores 35 MP instantly.',
    descriptionId: 'Memulihkan 35 MP seketika.',
    icon: '💧',
    value: 15,
    consumableEffect: { mpRestore: 35 },
  },
  {
    id: 'sword_starter',
    name: 'Apprentice Steel Blade',
    nameId: 'Pedang Baja Pemula',
    type: 'weapon',
    rarity: 'common',
    description: 'A well-balanced standard sword issued to new adventurers.',
    descriptionId: 'Pedang standar seimbang untuk petualang baru.',
    icon: '🗡️',
    value: 30,
    stats: { attack: 8 },
    equipped: true,
  },
  {
    id: 'armor_starter',
    name: 'Adventurer Tunic',
    nameId: 'Jubah Petualang',
    type: 'armor',
    rarity: 'common',
    description: 'Sturdy leather gear granting light protection.',
    descriptionId: 'Perlengkapan kulit kokoh pemberi pertahanan ringan.',
    icon: '🛡️',
    value: 25,
    stats: { defense: 5, hp: 20 },
    equipped: true,
  },
];

export const CHEST_LOOT_POOL: Item[] = [
  {
    id: 'sword_crystal',
    name: 'Azure Crystal Claymore',
    nameId: 'Pedang Kristal Biru',
    type: 'weapon',
    rarity: 'epic',
    description: 'Forged from ancient resonant crystals. Radiates pure arcane strike power.',
    descriptionId: 'Ditempa dari kristal kuno. Memancarkan daya serang sihir murni.',
    icon: '⚔️',
    value: 180,
    stats: { attack: 28, mp: 30 },
  },
  {
    id: 'armor_plate_knight',
    name: 'Aegis Guardian Armor',
    nameId: 'Zirah Pelindung Ksatria',
    type: 'armor',
    rarity: 'rare',
    description: 'Heavy enchanted plate armor blessed by ancient temple wardens.',
    descriptionId: 'Zirah pelat berat dengan berkat pelindung kuil kuno.',
    icon: '🛡️',
    value: 150,
    stats: { defense: 18, hp: 60 },
  },
  {
    id: 'ring_valiant',
    name: 'Ring of the Swift Wind',
    nameId: 'Cincin Angin Gesit',
    type: 'accessory',
    rarity: 'rare',
    description: 'Imbues the wearer with agility and swift movement.',
    descriptionId: 'Memberikan pemakainya kelincahan dan kecepatan gerak ekstra.',
    icon: '💍',
    value: 120,
    stats: { speed: 4, attack: 6 },
  },
  {
    id: 'potion_hp_large',
    name: 'Greater Elixir of Life',
    nameId: 'Eliksir Kehidupan Murni',
    type: 'consumable',
    rarity: 'rare',
    description: 'Restores 120 HP completely.',
    descriptionId: 'Memulihkan 120 HP secara penuh.',
    icon: '✨',
    value: 50,
    consumableEffect: { hpRestore: 120 },
  },
];

export const INITIAL_QUESTS: Quest[] = [
  {
    id: 'quest_talk_elder',
    title: 'Whispers of Eldoria',
    titleId: 'Panggilan Lembah Kuno',
    description: 'Speak with Elder Vaelen near the village sanctuary fountain.',
    descriptionId: 'Bicaralah dengan Tetua Vaelen di dekat air mancur kuil desa.',
    targetType: 'talk',
    targetCount: 1,
    currentCount: 0,
    rewardExp: 50,
    rewardGold: 30,
    completed: false,
    claimed: false,
    requiredLevel: 1,
  },
  {
    id: 'quest_cull_slimes',
    title: 'Slime Menace',
    titleId: 'Ancaman Monster Lendir',
    description: 'Defeat 4 Grassland Slimes infesting the outer meadows.',
    descriptionId: 'Kalahkan 4 Slime Rumput yang mengganggu padang rumput luar.',
    targetType: 'kill',
    targetEnemy: 'slime',
    targetCount: 4,
    currentCount: 0,
    rewardExp: 100,
    rewardGold: 60,
    rewardItem: {
      id: 'potion_hp_medium',
      name: 'Vitality Draught',
      nameId: 'Ramuan Vitalitas',
      type: 'consumable',
      rarity: 'common',
      description: 'Restores 75 HP.',
      descriptionId: 'Memulihkan 75 HP.',
      icon: '🧪',
      value: 30,
      consumableEffect: { hpRestore: 75 },
    },
    completed: false,
    claimed: false,
    requiredLevel: 1,
  },
  {
    id: 'quest_skeleton_threat',
    title: 'Cursed Crypt Sentinels',
    titleId: 'Kutukan Prajurit Tengkorak',
    description: 'Purge 3 Skeleton Warriors wandering near the ancient ruins stone pillars.',
    descriptionId: 'Basmi 3 Prajurit Tengkorak yang berkeliaran di dekat pilar reruntuhan kuno.',
    targetType: 'kill',
    targetEnemy: 'skeleton',
    targetCount: 3,
    currentCount: 0,
    rewardExp: 180,
    rewardGold: 120,
    completed: false,
    claimed: false,
    requiredLevel: 2,
  },
  {
    id: 'quest_cull_goblins',
    title: 'Coastal Raiders',
    titleId: 'Serbuan Goblin Pesisir',
    description: 'Defeat 4 Goblins lurking along the southern beach and docks.',
    descriptionId: 'Kalahkan 4 Goblin yang mengintai di sepanjang pantai selatan dan dermaga.',
    targetType: 'kill',
    targetEnemy: 'goblin',
    targetCount: 4,
    currentCount: 0,
    rewardExp: 220,
    rewardGold: 150,
    completed: false,
    claimed: false,
    requiredLevel: 2,
  },
  {
    id: 'quest_magma_cull',
    title: 'Crater Inferno',
    titleId: 'Pembersihan Magma Slime',
    description: 'Extinguish 3 blazing Magma Slimes patrolling the northern caldera slope.',
    descriptionId: 'Padamkan 3 Magma Slime berapi yang berpatroli di lereng kawah utara.',
    targetType: 'kill',
    targetEnemy: 'magma_slime',
    targetCount: 3,
    currentCount: 0,
    rewardExp: 280,
    rewardGold: 180,
    completed: false,
    claimed: false,
    requiredLevel: 3,
  },
  {
    id: 'quest_golem_hunt',
    title: 'Heart of Stone',
    titleId: 'Penjaga Batu Kuno Golem',
    description: 'Shatter 2 Ancient Stone Golems guarding the eastern mystic forest.',
    descriptionId: 'Hancurkan 2 Golem Batu Kuno penjaga hutan mistis timur.',
    targetType: 'kill',
    targetEnemy: 'golem',
    targetCount: 2,
    currentCount: 0,
    rewardExp: 380,
    rewardGold: 240,
    completed: false,
    claimed: false,
    requiredLevel: 4,
  },
  {
    id: 'quest_spider_nest',
    title: 'Venomous Shadows',
    titleId: 'Sarang Laba-Laba Raksasa',
    description: 'Exterminate 3 Giant Forest Spiders in the eastern forest depths.',
    descriptionId: 'Basmi 3 Laba-laba Raksasa di kedalaman hutan timur.',
    targetType: 'kill',
    targetEnemy: 'spider',
    targetCount: 3,
    currentCount: 0,
    rewardExp: 350,
    rewardGold: 220,
    completed: false,
    claimed: false,
    requiredLevel: 3,
  },
  {
    id: 'quest_defeat_boss',
    title: 'The Titan of the Abyss',
    titleId: 'Kebangkitan Sang Titan Kuno',
    description: 'Venture into the volcanic crater arena and slay the Colossal Golem Boss!',
    descriptionId: 'Masuki arena kawah misterius dan kalahkan Sang Colossal Titan Golem!',
    targetType: 'boss',
    targetEnemy: 'boss',
    targetCount: 1,
    currentCount: 0,
    rewardExp: 500,
    rewardGold: 350,
    rewardItem: {
      id: 'sword_titanslayer',
      name: 'Titanslayer Solar Edge',
      nameId: 'Pedang Surya Pembasmi Titan',
      type: 'weapon',
      rarity: 'legendary',
      description: 'The supreme blade radiating blinding solar flames.',
      descriptionId: 'Pedang agung legendaris yang bersinar dengan bara api surya.',
      icon: '🔥',
      value: 500,
      stats: { attack: 45, defense: 10, hp: 50 },
    },
    completed: false,
    claimed: false,
    requiredLevel: 3,
  },
  {
    id: 'quest_discover_valkragor',
    title: 'Highland Frontier',
    titleId: 'Perjalanan ke Benteng Val-Kragor',
    description: 'Cross the misty chasm suspension bridge to the far east and discover the highland fortress village of Val-Kragor.',
    descriptionId: 'Lintasi jembatan gantung jurang berkabut di timur jauh dan temukan Desa Benteng Val-Kragor di dataran tinggi.',
    targetType: 'talk',
    targetCount: 1,
    currentCount: 0,
    rewardExp: 350,
    rewardGold: 250,
    completed: false,
    claimed: false,
    requiredLevel: 2,
  },
  {
    id: 'quest_frostpeak_wolves',
    title: 'Frostfang Threat',
    titleId: 'Perburuan Serigala Frostpeak',
    description: 'Purge 4 Frostfang Wolves prowling the icy crags of Frostpeak Summit.',
    descriptionId: 'Kalahkan 4 Serigala Frostfang yang berkeliaran di puncak beku Frostpeak.',
    targetType: 'kill',
    targetEnemy: 'frost_wolf',
    targetCount: 4,
    currentCount: 0,
    rewardExp: 420,
    rewardGold: 300,
    rewardItem: {
      id: 'potion_elixir_supreme',
      name: 'Glacial Elixir of Vigor',
      nameId: 'Eliksir Es Pembasmi Beku',
      type: 'consumable',
      rarity: 'rare',
      description: 'Restores 180 HP and 60 Mana instantly.',
      descriptionId: 'Memulihkan 180 HP dan 60 Mana secara instan.',
      icon: '❄️',
      value: 120,
      consumableEffect: { hpRestore: 180, mpRestore: 60 },
    },
    completed: false,
    claimed: false,
    requiredLevel: 3,
  },
  {
    id: 'quest_shadowfen_hydra',
    title: 'Marsh of Shadows',
    titleId: 'Pembersihan Rawa Bayangan',
    description: 'Defeat 3 Toxic Swamp Crawlers infesting the dark waters of Shadowfen Marsh.',
    descriptionId: 'Basmi 3 Monster Rawa Beracun yang mencemari air gelap di Rawa Bayangan barat.',
    targetType: 'kill',
    targetEnemy: 'swamp_crawler',
    targetCount: 3,
    currentCount: 0,
    rewardExp: 380,
    rewardGold: 240,
    completed: false,
    claimed: false,
    requiredLevel: 3,
  },
  {
    id: 'quest_discover_astraea',
    title: 'Crown of the East',
    titleId: 'Perjalanan ke Ibukota Kerajaan Emas Astraea',
    description: 'Travel east beyond Val-Kragor along the imperial golden road to reach the majestic capital kingdom of Astraea.',
    descriptionId: 'Melangkahlah ke timur melewati Benteng Val-Kragor menyusuri jalan raya kerajaan untuk menemukan Ibukota Megah Astraea dan Istana Kaisar Aurelius.',
    targetType: 'talk',
    targetCount: 1,
    currentCount: 0,
    rewardExp: 800,
    rewardGold: 600,
    completed: false,
    claimed: false,
    requiredLevel: 4,
  },
];

export const DIALOGUES: Record<string, DialogueNode> = {
  elder_intro: {
    id: 'elder_intro',
    speaker: 'Tetua Vaelen',
    speakerTitle: 'Penjaga Kuil Eldoria',
    text: 'Greetings, young brave wanderer. The ancient crystal obelisks are flickering with ominous shadows.',
    textId: 'Salam, pengelana muda yang pemberani. Menara kristal kuno mulai bergetar karena bayangan kegelapan.',
    avatarIcon: '🧙‍♂️',
    options: [
      {
        label: 'What danger threatens our valley, Elder?',
        labelId: 'Bahaya apa yang mengancam lembah kita, Tetua?',
        nextId: 'elder_lore',
      },
      {
        label: 'I am ready to fight! Tell me what to do.',
        labelId: 'Saya siap bertarung! Berikan saya tugas.',
        nextId: 'elder_quest',
      },
    ],
  },
  elder_lore: {
    id: 'elder_lore',
    speaker: 'Tetua Vaelen',
    speakerTitle: 'Penjaga Kuil Eldoria',
    text: 'A long-slumbering Obsidian Titan has awakened in the northern volcanic crags. Its dark aura is spawning feral slimes and undead skeleton knights.',
    textId: 'Sang Titan Obsidian yang tertidur ribuan tahun kini bangkit di kawah utara. Auranya memanggil monster lendir dan prajurit tengkorak terkutuk.',
    avatarIcon: '🧙‍♂️',
    options: [
      {
        label: 'I will purge the monsters and slay the Titan!',
        labelId: 'Saya akan basmi monster itu dan mengalahkan sang Titan!',
        nextId: 'elder_quest',
      },
      {
        label: 'Could you bless and heal my wounds first?',
        labelId: 'Bisa sembuhkan luka dan pulihkan tenaga saya terlebih dahulu?',
        action: 'heal',
      },
    ],
  },
  elder_quest: {
    id: 'elder_quest',
    speaker: 'Tetua Vaelen',
    speakerTitle: 'Penjaga Kuil Eldoria',
    text: 'Take this knowledge. Start by clearing the slimes near the meadow and harvest treasure chests hidden behind the ancient pillars to strengthen your gear.',
    textId: 'Bagus. Mulailah dengan membersihkan slime di padang rumput dan cari peti harta karun di antara pilar kuno untuk memperkuat senjatamu!',
    avatarIcon: '🧙‍♂️',
    options: [
      {
        label: 'Understood! I will protect Eldoria.',
        labelId: 'Dimengerti! Saya akan lindungi Eldoria.',
        action: 'acceptQuest',
        questId: 'quest_talk_elder',
      },
    ],
  },
  healed_blessing: {
    id: 'healed_blessing',
    speaker: 'Tetua Vaelen',
    speakerTitle: 'Penjaga Kuil Eldoria',
    text: 'May the light of Eldoria renew your vigor! Your wounds are cleansed and your spirit is refreshed.',
    textId: 'Semoga cahaya suci Eldoria memulihkan ragamu! Semua lukamu telah sembuh dan kekuatanmu pulih seutuhnya.',
    avatarIcon: '✨',
    options: [
      {
        label: 'Thank you, Elder!',
        labelId: 'Terima kasih, Tetua!',
        action: 'close',
      },
    ],
  },
  guard_intro: {
    id: 'guard_intro',
    speaker: 'Kapten Ronald',
    speakerTitle: 'Panglima Penjaga Gerbang Eldoria',
    text: 'Halt, adventurer! Beyond this gate lies danger. The northern crags crawl with Magma Slimes, and the ancient western ruins are overrun with Skeletons and Necromancers.',
    textId: 'Berhenti, petualang! Di luar gerbang ini sangat berbahaya. Tebing utara dipenuhi Magma Slime, reruntuhan barat dihuni Prajurit Tengkorak & Penyihir Hitam, dan hutan timur sarang Golem serta Laba-laba raksasa!',
    avatarIcon: '🛡️',
    options: [
      {
        label: 'Any tactical advice for combat?',
        labelId: 'Ada saran taktik dalam bertarung melawan mereka?',
        nextId: 'guard_tips',
      },
      {
        label: 'I am ready for anything. I will keep the village safe!',
        labelId: 'Saya siap menghadapi segalanya demi keamanan desa!',
        action: 'close',
      },
    ],
  },
  guard_tips: {
    id: 'guard_tips',
    speaker: 'Kapten Ronald',
    speakerTitle: 'Panglima Penjaga Gerbang Eldoria',
    text: 'Maintain distance against Golems and the Obsidian Titan—their shockwaves are devastating. Against mages, close in fast with dashes! Upgrade your level to 5, 10, and 15 to unlock legendary forms and power!',
    textId: 'Jaga jarak dari Golem dan Sang Titan—serangan gempa mereka mematikan! Hadapi Penyihir Tengkorak dengan mendekat cepat menggunakan Dash! Naikkan levelmu ke 5, 10, dan 15 untuk membuka wujud tempur legendaris dan kemampuan role yang dahsyat!',
    avatarIcon: '⚔️',
    options: [
      {
        label: 'Thank you for the advice, Captain!',
        labelId: 'Terima kasih atas saran taktiknya, Kapten!',
        action: 'close',
      },
    ],
  },
  alchemist_intro: {
    id: 'alchemist_intro',
    speaker: 'Anya',
    speakerTitle: 'Alkemis & Herbalis Eldoria',
    text: 'Greetings, brave soul! I distill herbal potions from rare roots gathered at the eastern forest. Would you like a fresh batch of vitality elixir?',
    textId: 'Salam, pengembara pemberani! Saya meracik ramuan herbal alami dari akar hutan mistis. Mau berbelanja ramuan pemulih atau butuh bantuan penyembuhan luka?',
    avatarIcon: '🌿',
    options: [
      {
        label: 'Open Potion & Elixir Shop',
        labelId: '🧪 Beli Ramuan Darah, Mana & Eliksir (Buka Toko)',
        action: 'openShop',
        shopType: 'potions',
      },
      {
        label: 'Please heal and restore my health, Anya!',
        labelId: '✨ Tolong sembuhkan luka dan pulihkan energiku sekarang!',
        action: 'heal',
      },
      {
        label: 'What ingredients do you recommend?',
        labelId: 'Apa saran racikan herbalmu untuk menghadapi racun laba-laba?',
        nextId: 'alchemist_lore',
      },
      {
        label: 'Good luck with brewing, Anya!',
        labelId: 'Sampai jumpa, Anya!',
        action: 'close',
      },
    ],
  },
  alchemist_lore: {
    id: 'alchemist_lore',
    speaker: 'Anya',
    speakerTitle: 'Alkemis & Herbalis Eldoria',
    text: 'Forest spiders carry lethal neurotoxins. Drink plenty of health potions, and look out for chests scattered across the world—they contain supreme healing elixirs!',
    textId: 'Laba-laba hutan membawa racun mematikan. Selalu bawa ramuan herbal, dan cari peti harta karun tersembunyi di pantai, reruntuhan, dan hutan mistis untuk ramuan penyembuh super!',
    avatarIcon: '🧪',
    options: [
      {
        label: 'Let me check your potions!',
        labelId: '🧪 Tunjukkan persediaan ramuanmu sekarang!',
        action: 'openShop',
        shopType: 'potions',
      },
      {
        label: 'Thank you, Anya!',
        labelId: 'Terima kasih informasinya, Anya!',
        action: 'close',
      },
    ],
  },
  blacksmith_torvald: {
    id: 'blacksmith_torvald',
    speaker: 'Master Torvald',
    speakerTitle: 'Pandai Besi Legendaris',
    text: 'Clang! Hah, you look like you could swing a sword or cast a blazing spell. Keep leveling up—every 5 levels, your armor shines brighter, your weapons glow with elemental runes, and your wings awaken!',
    textId: 'Dentang! Hah, tubuhmu terlatih dengan baik! Butuh senjata baja tajam, tongkat sihir berenergi, busur akurat, atau ingin menempa senjatamu agar semakin mematikan?',
    avatarIcon: '🔨',
    options: [
      {
        label: 'Open Weapon & Forge Shop',
        labelId: '🔨 Buka Toko Senjata & Tempa Perlengkapan',
        action: 'openShop',
        shopType: 'blacksmith',
      },
      {
        label: 'How does weapon evolution work?',
        labelId: 'Bagaimana evolusi senjata dan wujud bekerja saat naik level?',
        nextId: 'blacksmith_lore',
      },
      {
        label: 'I will forge my destiny in battle!',
        labelId: 'Saya akan buktikan kekuatan saya di medan tempur!',
        action: 'close',
      },
    ],
  },
  blacksmith_lore: {
    id: 'blacksmith_lore',
    speaker: 'Master Torvald',
    speakerTitle: 'Pandai Besi Legendaris',
    text: 'At level 5, you achieve Adept rank with glowing rune steel. At level 10, Master rank bestows golden armor and orbiting mana crystals. At level 15, you awaken the Mythic Archon form with divine wings and unmatched damage!',
    textId: 'Pada level 5, kamu meraih gelar Terlatih dengan rune bercahaya. Pada level 10, kamu meraih gelar Elit dengan zirah naga emas dan kristal mengorbit. Pada level 15, kamu membangkitkan Wujud Legenda dengan sayap bercahaya dan daya hancur berlipat ganda!',
    avatarIcon: '🔥',
    options: [
      {
        label: 'Show me your weapons and forge!',
        labelId: '🔨 Tunjukkan senjata dan bengkel tempamu!',
        action: 'openShop',
        shopType: 'blacksmith',
      },
      {
        label: 'Incredible! I will train hard.',
        labelId: 'Luar biasa! Saya akan terus berlatih dan naik level.',
        action: 'close',
      },
    ],
  },
  bard_lyra: {
    id: 'bard_lyra',
    speaker: 'Lyra',
    speakerTitle: 'Penyanyi Kelana & Penutur Kisah',
    text: '🎶 "O ancient crater where obsidian sleeps, a colossus waits while the mountain weeps..." Would you like to hear the ballad of the Obsidian Titan?',
    textId: '🎶 "Dengarkanlah angin berbisik di antara batu kuno... Sang Titan Obsidian terlelap di kawah utara, menunggu pahlawan sejati yang mampu menembus badai magma..." Mau mendengarkan laguku?',
    avatarIcon: '🪕',
    options: [
      {
        label: 'Tell me about the Titan!',
        labelId: 'Ceritakan padaku tentang Sang Titan Obsidian!',
        nextId: 'bard_titan_tale',
      },
      {
        label: 'Beautiful tune, Lyra! Keep singing.',
        labelId: 'Lagu yang merdu, Lyra! Teruslah bernyanyi untuk warga desa.',
        action: 'close',
      },
    ],
  },
  bard_titan_tale: {
    id: 'bard_titan_tale',
    speaker: 'Lyra',
    speakerTitle: 'Penyanyi Kelana & Penutur Kisah',
    text: 'The Obsidian Titan was sealed centuries ago in the northern volcanic caldera. Only warriors who harness their ultimate skill can shatter his volcanic core!',
    textId: 'Titan Obsidian disegel berabad-abad lalu di kawah vulkanik utara. Hanya ksatria berlevel tinggi dengan serangan pamungkas yang sanggup menghancurkan inti magma batu legam miliknya!',
    avatarIcon: '✨',
    options: [
      {
        label: 'I will defeat him!',
        labelId: 'Saya yang akan menuntaskan takdir itu!',
        action: 'close',
      },
    ],
  },
  fisherman_joko: {
    id: 'fisherman_joko',
    speaker: 'Pak Joko',
    speakerTitle: 'Nelayan Pesisir Pantai Selatan',
    text: 'Ah, the fresh sea breeze! Watch your step along the pier. Goblins often scout the shore from the eastern shoals. Open the chest by the dock for some extra supplies!',
    textId: 'Segarnya angin laut selatan! Hati-hati saat berjalan di dermaga kayu ini. Saya punya perbekalan ikan bakar hangat pemulih tenaga dan mutiara laut yang indah!',
    avatarIcon: '🎣',
    options: [
      {
        label: 'Open Seafood & Provisions Store',
        labelId: '🐟 Beli Perbekalan Ikan Bakar & Hasil Laut (Buka Toko)',
        action: 'openShop',
        shopType: 'general',
      },
      {
        label: 'Thanks for the tip, Pak Joko!',
        labelId: 'Terima kasih infonya, Pak Joko! Semoga tangkapan ikannya melimpah.',
        action: 'close',
      },
    ],
  },
  villager_kael: {
    id: 'villager_kael',
    speaker: 'Kael the Scout',
    speakerTitle: 'Pedagang Pasar Gelap & Penjelajah Reruntuhan',
    text: 'Ssst... looking for power beyond ordinary weapons? I trade ancient relics and dangerous obsidian runes from the ruins.',
    textId: 'Ssst... mencari kekuatan di luar batas nalar? Aku mengumpulkan artefak langka, batu rune hitam, dan ramuan darah terlarang dari kedalaman reruntuhan kuno!',
    avatarIcon: '🧑',
    options: [
      {
        label: 'Open Black Market / Relics Shop',
        labelId: '🗝️ Lihat Artefak Langka & Pusaka Rahasia (Buka Toko Gelap)',
        action: 'openShop',
        shopType: 'mystic',
      },
      {
        label: 'Do not worry, I will protect this village.',
        labelId: 'Tetap waspada, Kael! Saya akan pastikan desa ini aman.',
        action: 'close',
      },
    ],
  },
  villager_maya: {
    id: 'villager_maya',
    speaker: 'Maya the Outfitter',
    speakerTitle: 'Pedagang Zirah & Perlengkapan Tempur',
    text: 'Welcome adventurer! I stock heavy steel plate armor, fine mystic robes, stalker vests, and enchanted rings!',
    textId: 'Selamat datang, ksatria! Aku menyediakan berbagai macam pelindung tubuh terbaik: Zirah pelat baja ksatria, jubah sutra magis, rompi kulit pengintai, serta cincin berenergi!',
    avatarIcon: '🛡️',
    options: [
      {
        label: 'Open Armor & Equipment Shop',
        labelId: '🛡️ Buka Toko Zirah, Helm & Aksesori Perlengkapan',
        action: 'openShop',
        shopType: 'equipment',
      },
      {
        label: 'Thank you, Maya!',
        labelId: 'Terima kasih keramahannya, Maya!',
        action: 'close',
      },
    ],
  },
  commander_brann: {
    id: 'commander_brann',
    speaker: 'Komandan Brann',
    speakerTitle: 'Panglima Benteng Val-Kragor',
    text: 'Greetings, traveler! You crossed the misty chasm to reach Val-Kragor. We stand as the highland shield against the frost beasts of the northern peaks.',
    textId: 'Salam, petualang gagah! Kau berhasil menyeberangi jembatan jurang berkabut hingga tiba di Desa Benteng Val-Kragor. Kami adalah benteng pertahanan terakhir dataran tinggi melawan serbuan monster serigala es dan golem beku.',
    avatarIcon: '🐺',
    options: [
      {
        label: 'How can I assist the fortress garrison, Commander?',
        labelId: 'Apa yang bisa saya bantu untuk pertahanan benteng ini, Komandan?',
        nextId: 'brann_quest_info',
      },
      {
        label: 'Tell me about the frozen peak above.',
        labelId: 'Ceritakan tentang puncak gunung es di atas sana.',
        nextId: 'brann_frostpeak_lore',
      },
      {
        label: 'I will inspect the fortress ramparts.',
        labelId: 'Saya akan berkeliling memeriksa benteng ini.',
        action: 'close',
      },
    ],
  },
  brann_quest_info: {
    id: 'brann_quest_info',
    speaker: 'Komandan Brann',
    speakerTitle: 'Panglima Benteng Val-Kragor',
    text: 'Frostfang wolves have been descending from the high glaciers. Slay them to secure our supply line! Visit Goran at the forge for reinforced highland armor.',
    textId: 'Kawanan Serigala Frostfang mulai menuruni gletser es dan mengancam jalur pasokan benteng. Basmi mereka untuk mengamankan perbatasan! Jangan lupa temui Goran sang pandai besi gunung untuk memperkuat persenjataanmu.',
    avatarIcon: '⚔️',
    options: [
      {
        label: 'I will eliminate the wolves!',
        labelId: 'Saya akan tumpas kawanan serigala es itu!',
        action: 'acceptQuest',
        questId: 'quest_frostpeak_wolves',
      },
      {
        label: 'Understood, Commander!',
        labelId: 'Siap laksanakan, Komandan!',
        action: 'close',
      },
    ],
  },
  brann_frostpeak_lore: {
    id: 'brann_frostpeak_lore',
    speaker: 'Komandan Brann',
    speakerTitle: 'Panglima Benteng Val-Kragor',
    text: 'At the summit lies an ancient Cryo Altar sealed in eternal rime. It is said an ancient weapon lies resting in the glacial chest guarded by ice spirits.',
    textId: 'Di puncak salju abadi terdapat Kuil Es Kuno yang diselimuti es abadi. Legenda mengatakan ada peti pusaka beku berisi senjata legendaris yang dijaga roh es kuno.',
    avatarIcon: '🏔️',
    options: [
      {
        label: 'I will explore the Cryo Altar!',
        labelId: 'Saya akan meneliti Kuil Es tersebut!',
        action: 'close',
      },
    ],
  },
  seer_elora: {
    id: 'seer_elora',
    speaker: 'Peramal Elora',
    speakerTitle: 'Ahli Nujum & Penjaga Bintang Surgawi',
    text: 'The stars whisper of converging fates. The flames in the north and the deep frost here in the east are stirring.',
    textId: 'Bintang-bintang surgawi berbisik... Dua kekuatan purba sedang bergejolak: api kawah Titan di utara dan badai es di puncak timur. Aku bisa menyucikan jiwa dan memulihkan seluruh energimu dengan berkat bintang.',
    avatarIcon: '🔮',
    options: [
      {
        label: 'Bestow your celestial blessing upon me.',
        labelId: 'Berikan berkat bintang untuk menyembuhkan seluruh HP & Mana saya!',
        action: 'heal',
      },
      {
        label: 'What do the stars reveal about the far west?',
        labelId: 'Apa yang dilihat bintang mengenai rawa berkabut di barat jauh?',
        nextId: 'seer_shadowfen_lore',
      },
      {
        label: 'Thank you, Seer Elora.',
        labelId: 'Terima kasih atas bimbingannya, Elora.',
        action: 'close',
      },
    ],
  },
  seer_shadowfen_lore: {
    id: 'seer_shadowfen_lore',
    speaker: 'Peramal Elora',
    speakerTitle: 'Ahli Nujum & Penjaga Bintang Surgawi',
    text: 'Beyond the ancient ruins lies the Shadowfen Marsh. Giant glowing mushrooms pulse with toxic spores. Hidden among the mangrove roots lies a smuggler chest of forgotten gold.',
    textId: 'Di sebelah barat reruntuhan kuno terbentang Rawa Bayangan (Shadowfen). Jamur raksasa bercahaya melepaskan spora beracun. Di balik akar bakau purba, terdapat peti tersembunyi para penyelundup!',
    avatarIcon: '🌌',
    options: [
      {
        label: 'I will brave the poisonous swamp!',
        labelId: 'Saya akan selidiki rawa berkabut itu!',
        action: 'acceptQuest',
        questId: 'quest_shadowfen_hydra',
      },
      {
        label: 'I will be cautious.',
        labelId: 'Saya akan ekstra hati-hati.',
        action: 'close',
      },
    ],
  },
  frostsmith_goran: {
    id: 'frostsmith_goran',
    speaker: 'Goran Pandai Besi',
    speakerTitle: 'Master Tempa Dataran Tinggi Val-Kragor',
    text: 'Clang! The mountain cold requires hard steel! I forge weapons cooled in glacier water. Need elite fortress broadswords, frost staves, or want to enhance your gear?',
    textId: 'Dentang! Dinginnya gunung membutuhkan baja paling keras! Aku menempa senjata dengan pendinginan air es gletser. Butuh pedang tebas badai es, busur elang salju, atau ingin menempa senjatamu?',
    avatarIcon: '🔨',
    options: [
      {
        label: 'Open Highland Armory & Forge',
        labelId: '⚔️ Buka Bengkel Senjata & Zirah Benteng (Beli & Tempa)',
        action: 'openShop',
        shopType: 'blacksmith',
      },
      {
        label: 'Your work is remarkable, Goran!',
        labelId: 'Keahlian tempamu sangat hebat, Goran!',
        action: 'close',
      },
    ],
  },
  guard_valkragor: {
    id: 'guard_valkragor',
    speaker: 'Prajurit Penjaga Benteng',
    speakerTitle: 'Garis Depan Pertahanan Val-Kragor',
    text: 'Welcome to Fortress Village Val-Kragor! Commander Brann is waiting near the central keep firepit.',
    textId: 'Selamat datang di Desa Benteng Val-Kragor! Masuklah, Komandan Brann ada di depan perapian utama dan Goran ada di bengkel tempa.',
    avatarIcon: '🛡️',
    options: [
      {
        label: 'Thank you, Sentinel!',
        labelId: 'Terima kasih, Penjaga!',
        action: 'close',
      },
    ],
  },
  emperor_aurelius: {
    id: 'emperor_aurelius',
    speaker: 'Kaisar Aurelius Astraea',
    speakerTitle: 'Penguasa Tertinggi Ibukota Kekaisaran Emas',
    text: 'Welcome, champion, to Astraea, the Golden Crown of the Continent! Only those of true valor reach our radiant gates.',
    textId: 'Selamat datang, Sang Pahlawan, di Ibukota Kekaisaran Emas Astraea! Jarang sekali pengelana biasa mampu melintasi benua hingga menginjakkan kaki di istana matahari kami.',
    avatarIcon: '👑',
    options: [
      {
        label: 'Receive the Imperial Sun Blessing (Heal HP & MP)',
        labelId: '✨ Terima Berkat Matahari Kekaisaran (Pulihkan Penuh HP & Mana)',
        action: 'heal',
      },
      {
        label: 'Tell me of this great empire, Your Majesty.',
        labelId: 'Ceritakan tentang kejayaan Kekaisaran Astraea, Paduka Kaisar.',
        nextId: 'aurelius_lore',
      },
      {
        label: 'Honor to Astraea and the Golden Sun!',
        labelId: 'Hormat tertinggi untuk kejayaan Astraea dan Sang Surya Emas!',
        action: 'close',
      },
    ],
  },
  aurelius_lore: {
    id: 'aurelius_lore',
    speaker: 'Kaisar Aurelius Astraea',
    speakerTitle: 'Penguasa Tertinggi Ibukota Kekaisaran Emas',
    text: 'Astraea was built upon celestial ley lines. The Fountain of Immortality before my palace has flowed with life mana for thousands of years.',
    textId: 'Astraea didirikan di atas titik simpul energi kosmik benua. Air Mancur Keabadian di alun-alun istana telah mengalirkan intisari kehidupan murni selama ribuan tahun. Siapa pun yang berjuang dengan kehormatan akan diberkati kekuatan tanpa batas.',
    avatarIcon: '☀️',
    options: [
      {
        label: 'I will honor the kingdom, Your Majesty!',
        labelId: 'Saya akan selalu menjunjung tinggi kehormatan kekaisaran, Paduka!',
        action: 'close',
      },
    ],
  },
  marshal_vane: {
    id: 'marshal_vane',
    speaker: 'Panglima Perang Vane',
    speakerTitle: 'Panglima Tertinggi Legiun Astraea',
    text: 'Halt, warrior! State your allegiance. Ah, I see the light of high tiers upon your armor and skills. Astraea welcomes mighty heroes!',
    textId: 'Berhenti, pendekar! Tunjukkan auramu... Luar biasa, aku merasakan getaran kekuatan dahsyat dari tingkat level dan skill seranganmu. Legiun Emas Astraea menghormati pejuang berkemampuan sepertimu!',
    avatarIcon: '⚔️',
    options: [
      {
        label: 'Where can I find worthy challenges and elite gear?',
        labelId: 'Di mana saya bisa menemukan tantangan dan persenjataan tingkat tinggi?',
        nextId: 'vane_advice',
      },
      {
        label: 'Hail to the Imperial Legion, Marshal!',
        labelId: 'Salam hormat untuk Legiun Kekaisaran, Panglima!',
        action: 'close',
      },
    ],
  },
  vane_advice: {
    id: 'vane_advice',
    speaker: 'Panglima Perang Vane',
    speakerTitle: 'Panglima Tertinggi Legiun Astraea',
    text: 'Visit Merchant Lyra at the Royal Bazaar for masterwork elixirs and celestial goods, or test your prowess in the northern Caldera against the Dragon!',
    textId: 'Kunjungilah Saudagar Lyra di Pasar Kerajaan untuk memperoleh ramuan dan perlengkapan pusaka terbaik, atau uji kekuatan skill tingkat tinggimu melawan naga api purba di Kaldera utara!',
    avatarIcon: '🛡️',
    options: [
      {
        label: 'Thank you for the guidance, Marshal!',
        labelId: 'Terima kasih banyak atas arahannya, Panglima Vane!',
        action: 'close',
      },
    ],
  },
  merchant_lyra: {
    id: 'merchant_lyra',
    speaker: 'Saudagar Kerajaan Lyra',
    speakerTitle: 'Penyedia Pusaka & Sutra Emas Kekaisaran',
    text: 'Welcome to the Astraea Royal Bazaar! I have collected the finest relics, elixirs, and wares from all corners of the world.',
    textId: 'Selamat datang di Pasar Kerajaan Astraea! Saya mengumpulkan barang-barang langka, ramuan pemulih legendaris, dan perlengkapan terkuat dari seantero penjuru benua.',
    avatarIcon: '💎',
    options: [
      {
        label: 'Browse Imperial Store & Wares',
        labelId: '🛒 Buka Toko Perlengkapan & Ramuan Kerajaan',
        action: 'openShop',
        shopType: 'mystic',
      },
      {
        label: 'May your business flourish, Lyra!',
        labelId: 'Semoga daganganmu selalu laris, Saudagar Lyra!',
        action: 'close',
      },
    ],
  },
  guard_astraea: {
    id: 'guard_astraea',
    speaker: 'Prajurit Gerbang Emas',
    speakerTitle: 'Pengawal Kehormatan Astraea',
    text: 'You stand before the gates of Astraea. Walk with reverence in the Emperor’s presence.',
    textId: 'Kau berdiri di hadapan Gerbang Agung Ibukota Astraea. Berjalanlah dengan penuh kehormatan di hadapan Paduka Kaisar.',
    avatarIcon: '🛡️',
    options: [
      {
        label: 'Thank you, Imperial Guard!',
        labelId: 'Terima kasih atas tugasmu, Prajurit!',
        action: 'close',
      },
    ],
  },
};

export interface RoleSkillDef {
  slot: 'basic' | 1 | 2 | 3 | 'jump';
  nameId: string;
  descId: string;
  icon: string;
  hotkey: string;
  costText?: string;
  costValue?: number;
  costType?: 'mp' | 'stamina';
}

export interface RoleConfig {
  id: 'warrior' | 'mage' | 'rogue';
  title: string;
  subtitle: string;
  icon: string;
  movementName: string;
  movementDesc: string;
  themeColor: string;
  vfxColor: string;
  basicAttack: RoleSkillDef;
  skill1: RoleSkillDef;
  skill2: RoleSkillDef;
  skill3: RoleSkillDef;
  jump: RoleSkillDef;
}

export const ROLE_CONFIGS: Record<'warrior' | 'mage' | 'rogue', RoleConfig> = {
  warrior: {
    id: 'warrior',
    title: 'Ksatria (Warrior)',
    subtitle: 'Ksatria Pelindung & Tebasan Pedang Baja',
    icon: '⚔️',
    movementName: 'Langkah Tegap Ksatria',
    movementDesc: 'Melangkah gagah dengan perisai terangkat menjaga tubuh, siap menangkis segala benturan.',
    themeColor: '#3b82f6',
    vfxColor: '#fbbf24',
    basicAttack: {
      slot: 'basic',
      nameId: 'Tebasan Pedang Baja',
      descId: 'Tebasan busur pedang dua tangan berkekuatan dahsyat dengan gelombang energi busur emas.',
      icon: '🗡️',
      hotkey: 'Klik',
    },
    skill1: {
      slot: 1,
      nameId: 'Pusaran Badai Baja',
      descId: 'Memutar pedang 360 derajat menciptakan tornado badai tajam yang melibas semua musuh di sekitarnya.',
      icon: '🌪️',
      hotkey: 'Q',
      costText: '15 MP',
      costValue: 15,
      costType: 'mp',
    },
    skill2: {
      slot: 2,
      nameId: 'Terjangan Perisai Suci',
      descId: 'Menerjang maju dengan kubah perisai emas memukul mundur musuh di depannya.',
      icon: '🛡️',
      hotkey: 'E',
      costText: '15 Stm',
      costValue: 15,
      costType: 'stamina',
    },
    skill3: {
      slot: 3,
      nameId: 'Benteng Besi Suci',
      descId: 'Menancapkan pedang dan mengangkat perisai memanggil kubah pelindung suci pemulih HP.',
      icon: '✨',
      hotkey: 'R',
      costText: '25 MP',
      costValue: 25,
      costType: 'mp',
    },
    jump: {
      slot: 'jump',
      nameId: 'Lompatan Berat',
      descId: 'Melompat bertenaga dengan dentuman tanah saat mendarat.',
      icon: '🦘',
      hotkey: 'Spasi',
    },
  },
  mage: {
    id: 'mage',
    title: 'Penyihir (Mage)',
    subtitle: 'Penguasa Rune & Peluru Energi Astral',
    icon: '🔮',
    movementName: 'Melayang Anggun (Mystic Hover)',
    movementDesc: 'Melayang mulus di atas tanah dengan partikel sihir berpendar di bawah telapak kaki.',
    themeColor: '#a855f7',
    vfxColor: '#00e5ff',
    basicAttack: {
      slot: 'basic',
      nameId: 'Peluru Energi Kristal',
      descId: 'Menembakkan bola sihir kristal bercahaya ke arah musuh dari jarak jauh (Ranged Attack).',
      icon: '✨',
      hotkey: 'Klik',
    },
    skill1: {
      slot: 1,
      nameId: 'Supernova Astral',
      descId: 'Menghantamkan tongkat ke bumi, memicu ledakan cincin rune kosmik ungu-cyan beradius luas.',
      icon: '🌌',
      hotkey: 'Q',
      costText: '15 MP',
      costValue: 15,
      costType: 'mp',
    },
    skill2: {
      slot: 2,
      nameId: 'Langkah Dimensi (Blink)',
      descId: 'Menembus ruang dan waktu untuk teleportasi instan ke depan dengan kilatan cahaya bintang.',
      icon: '⚡',
      hotkey: 'E',
      costText: '15 Stm',
      costValue: 15,
      costType: 'stamina',
    },
    skill3: {
      slot: 3,
      nameId: 'Hujan Cahaya Astral',
      descId: 'Memanggil pilar sinar surgawi dari langit yang memulihkan HP dan MP seketika.',
      icon: '🌟',
      hotkey: 'R',
      costText: '25 MP',
      costValue: 25,
      costType: 'mp',
    },
    jump: {
      slot: 'jump',
      nameId: 'Levitasi Udara',
      descId: 'Melayang anggun ke udara melawan gravitasi bumi.',
      icon: '🕊️',
      hotkey: 'Spasi',
    },
  },
  rogue: {
    id: 'rogue',
    title: 'Pembunuh Bayangan (Rogue)',
    subtitle: 'Siluman Berbelati Kembar & Serangan Kritis',
    icon: '🗡️',
    movementName: 'Sprint Siluman (Ninja Dash)',
    movementDesc: 'Berlari mencondongkan tubuh rendah dengan memegang dua belati terbalik berkecepatan tinggi.',
    themeColor: '#10b981',
    vfxColor: '#34d399',
    basicAttack: {
      slot: 'basic',
      nameId: 'Tebasan Belati Ganda (X-Slash)',
      descId: 'Tebasan silang super cepat menggunakan belati kembar beracun dengan jejak garis hijau zamrud.',
      icon: '⚔️',
      hotkey: 'Klik',
    },
    skill1: {
      slot: 1,
      nameId: 'Tarian 1000 Belati',
      descId: 'Rangkaian tusukan kilat beruntun mematikan dengan kemungkinan serangan kritikal berlipat.',
      icon: '🌪️',
      hotkey: 'Q',
      costText: '15 MP',
      costValue: 15,
      costType: 'mp',
    },
    skill2: {
      slot: 2,
      nameId: 'Langkah Siluman Bayangan',
      descId: 'Melesat maju secepat kilat meninggalkan jejak klon bayangan hitam dan kepulan asap.',
      icon: '💨',
      hotkey: 'E',
      costText: '15 Stm',
      costValue: 15,
      costType: 'stamina',
    },
    skill3: {
      slot: 3,
      nameId: 'Kabut Asap & Eliksir',
      descId: 'Menjatuhkan bom asap siluman, menyembuhkan luka dan meningkatkan kecepatan secara drastis.',
      icon: '🧪',
      hotkey: 'R',
      costText: '25 MP',
      costValue: 25,
      costType: 'mp',
    },
    jump: {
      slot: 'jump',
      nameId: 'Acrobat Roll',
      descId: 'Lompatan jungkir balik akrobatik yang lincah menembus celah musuh.',
      icon: '🤸‍♂️',
      hotkey: 'Spasi',
    },
  },
};
